#!/bin/sh /etc/rc.common
# Script for mounting the usb storage device in /dev/sda1

START=99
STOP=99

start() {
        echo start

        # commands to launch application
        if [ ! -d "/mnt/usb-storage" ]; then
            /bin/mkdir /mnt/usb-storage
        fi

        /bin/mount /dev/sda1 /mnt/usb-storage
}

stop() {          
        echo stop
        # do nothing
}
