#!/bin/bash

if [ $# -le 0 ]
then
    echo "Usage: $0 [FILE 1 TO ADD] [FILE 2 TO ADD] ... [FILE N TO ADD]"
    echo "E.g. $0 video.avi file_0_5.dat"
    exit 1
fi

# start listening to packets
#tcpdump -i wlan0 -s 1600 -w /mnt/usb-storage/capture-wlan0-ccnx$2-$3-$DATE &
#tcpdump -i eth1 -s 1600 -w /mnt/usb-storage/capture-eth1-ccnx$2-$3-$DATE &
tcpdump -i eth0 -s 1600 -w /mnt/usb-storage/capture-eth0-ccnx$2-$3-$DATE &

# start ccnd
ccnd &

# start ccnr (a CCNx repository of files)
if [ ! -d "/home/adamiaonr/Workbench/ccnx/files/tests/" ]; then

    mkdir -p /home/adamiaonr/Workbench/ccnx/files/
fi

cd /home/adamiaonr/Workbench/ccnx/files/

ccnr &

# cycle through arguments, put them in the CCNx repo
for FILE in "$@"
do

    ccnputfile ccnx:/home/adamiaonr/Workbench/ccnx/files/$FILE $FILE &

done

# for now, do not kill ccnd or the CCNx repo
killall tcpdump

exit

